import { NextPage } from 'next';
import Head from 'next/head';
import { Sidebar } from './Sidebar';
import { Toolbar } from './Toolbar';

const Layout: NextPage = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col h-full w-full h-screen">
        <Toolbar />
        <div className="flex flex-row flex-1 overflow-hidden">
          <Sidebar />
          {children}
          {/* <Sidebar /> */}
          {/* <Content /> */}
        </div>
      </main>
    </>
  );
};

export default Layout;
